# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b654ec6adac7da5ee0eafa4c87716a86b93d0ea96bea24f07f1b0077aedd37b75cd1e7fbece01352edd8b366cf62b23522d26087272aab9517b268cd1aac7c9c

test:
  secret_key_base: 2864cb4634be379818d7afb376bdb80a6e46d4b88fdca9e85d20c9dc9a0c0ce5c4ed007be1102ab998db242d2ea48ad622bc4c194156ce31d9b9562f438d37b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
